# Generated by Django 5.2.1 on 2025-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Age', models.PositiveSmallIntegerField(default=0)),
                ('Gender', models.CharField(max_length=10)),
                ('Weight', models.PositiveIntegerField(default=0)),
                ('Semester', models.PositiveSmallIntegerField(default=0)),
                ('StudentID', models.PositiveIntegerField()),
                ('AdmissionNumber', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
